### ISSUE TITLE
multiple ring menus

### ISSUE THREAD

**Issue by jsb** [jsb/RingMenu#1]
Allow the user to create several ring menus. Each of these menus would be summoned by a different key binding and would have its individual settings (action button range, appearance, etc).

**Comment by jsb** [comment]
[As noted](http://forum.nostalrius.org/viewtopic.php?f=63&t=18584&start=30#p233063), there could be an option to keep multiple ring menus open at the same time to allow the construction of circular action bars.

**Comment by jsb** [comment]
Also, consider the option of binding multiple RingMenus to the same toggle key, allowing the creation of simultaneous concentric RingMenus (as suggested [here](http://forum.nostalrius.org/viewtopic.php?f=63&t=18584&start=40#p320615)).

**Comment by hardtofin** [comment]
wonderful that you are working on it, thank you!

**Comment by jsb** [comment]
This has been implemented in 598d63d3a6f772209b54450c42322cefc4e9d988.
