### ISSUE TITLE
Release 1.0.3

### ISSUE THREAD

**Issue by leschalu** [jsb/RingMenu#15]
Hi. Will you accept pulls for [update](https://github.com/leschalu/RingMenu/releases/)? Here [commits](https://github.com/leschalu/RingMenu/commits/master)
How hard do you think it will be to port to classic?

**Comment by jsb** [comment]
Currently, I have no plans to maintain the Vanilla WoW version of this AddOn anymore.

Also, I'm not quite sure what your updates do.

**Comment by tunderix** [comment]
@jsb thanks a huge deal! Was just wondering if you are gonna do this or should I give you PR!
Really like your addon m8!

Did you have support for multiple rings? Or is it one only atm? Are you gonna do multiple rings in future?

**Comment by jsb** [comment]
@tunderix This release currently only supports a single ring (as in the Vanilla version). However, I have kept this feature in mind during the Classic rewrite. Internally, the code is already equipped to handle multiple rings; there is just currently no UI / settings to create or configure them. It's definitely planned for a future release.

Besides posting this AddOn to the pertinent repository sites (e.g. [wowinterface](https://www.wowinterface.com/downloads/info25110-RingMenu.html), [Will It Classic](https://willitclassic.com/view/SJEXFg94BF0CO9SEg8F1)), I didn't plan to do any advertising. If you want to do that, I'd certainly appreciate it, though!
