### ISSUE TITLE
Other bar?

### ISSUE THREAD

**Issue by Trurb** [jsb/RingMenu#21]
Hi,
Are there any place i can choose that bar the menu take from?
Or edit it my self?
Thx in advance

**Comment by jsb** [comment]
Yes! That's what the *First Button Slot* setting does. The first bar corresponds to button slot 1, and then every bar increases this value by 12, (i.e. 1, 13, 25, 37, etc.). For more info, see [this page](https://wowwiki.fandom.com/wiki/ActionSlot).

**Comment by Trurb** [comment]
Meaning on my UI the ringmenu use the bar marked with red. Are there anyway i can make it take one of the oter bars?
![ring](https://user-images.githubusercontent.com/30940805/63868819-732c6c00-c9b7-11e9-85bc-8ee8d3d5b280.jpg)

**Comment by jsb** [comment]
Yes, try out some other values for *First Button Slot*. It makes sense to increase the values in increments of 12 until you find a bar that is not used by your UI.
