### ISSUE TITLE
Unbound keybind when reloading ui

### ISSUE THREAD

**Issue by TheMumblingBum** [jsb/RingMenu#22]
Any time I log out or reload UI the keybind is wiped clean. This doesn't happen with any other addon in classic, is this happening to others?

**Comment by jsb** [comment]
Thanks for reporting. This might be related to [this API change](https://us.forums.blizzard.com/en/wow/t/ui-issue-savebindings-removed/206876) in Classic.

**Comment by x4my** [comment]
ye i have the same problem =( is they a other way to Bind Keys? Maybe in options.lua ?

**Comment by jsb** [comment]
I think 42b17cfc6b648ea718c7c57939cf2e08fa33a7d2 fixed it.

**Comment by jsb** [comment]
Should be fixed now. New release is [here](https://github.com/jsb/RingMenu/releases/tag/v.2.1.1). Please comment if the bug persists.
