### ISSUE TITLE
Option for RingMenu to Remain Open Until Toggled Closed

### ISSUE THREAD

**Issue by hammmy** [jsb/RingMenu#26]
Hi, I believe the 1.12 version of this addon has the option to change the behavior of the RingMenu keybind to toggle between having RingMenu visible or not, rather than the default behavior of closing RingMenu as soon as a button is clicked.  I would like this option in 1.13 if possible; it's invaluable for repetitive actions like summoning mage consumables from RingMenu!

Thank you!

**Comment by jsb** [comment]
In the current version of the AddOn, there's a "Close on Click" option that you can turn off. Does this do what you want?

**Comment by hammmy** [comment]
Yes!  I didn't have the latest version; sorry for the trouble.
