### ISSUE TITLE
Addon not appearing in Addon Menu - Wow CLassic

### ISSUE THREAD

**Issue by Vierz** [jsb/RingMenu#28]
I downloaded the last release and i cannot access the addon ingame. The addon is not appearing in the interface menu.

**Comment by Vierz** [comment]
I have the option to add the keybind but the /ringmenu is not working

**Comment by jsb** [comment]
This sounds to me like you might have downloaded the Vanilla version. Can you retry downloading the latest release from [here](https://github.com/jsb/RingMenu/releases)?

**Comment by reaktorblue** [comment]
I also have this problem in WoW Classic. I can see that RingMenu is loaded in the AddOns screen however, when I navigate to Interface Options -> AddOns, RingMenu is no longer listed.

I didn't have this issue in RingMenu v2.1.1

**Comment by jsb** [comment]
Unfortunately, I cannot reproduce this issue. Can you please try the following:
* Download the [AdvancedInterfaceOptions](https://github.com/Stanzilla/AdvancedInterfaceOptions) AddOn.
* Start the game, enable *Display Lua Errors* in AdvancedInterfaceOptions.
* Type `/console reloadui`
* Report any Lua errors that show up, if any.

**Comment by Vierz** [comment]
> 
> 
> This sounds to me like you might have downloaded the Vanilla version. Can you retry downloading the latest release from [here](https://github.com/jsb/RingMenu/releases)?

This was the issue, thank you.
