### ISSUE TITLE
RingMenu not popping up in options

### ISSUE THREAD

**Issue by kbmorales** [jsb/RingMenu#32]
First off, big fan of RingMenu! Used it plenty before.

For some reason, though I've dropped it the proper AddOns/ folder and can choose to enable it when logging in to WoW, the RingMenu doesn't appear in my Options > Interface > AddOns menu.

**Comment by kbmorales** [comment]
Find the Lua Error code here:

Message: Interface\AddOns\RingMenu\main.lua:2: attempt to call global 'LibStub' (a nil value)
Time: Sat Oct  5 13:35:42 2019
Count: 1
Stack: Interface\AddOns\RingMenu\main.lua:2: attempt to call global 'LibStub' (a nil value)
Interface\AddOns\RingMenu\main.lua:2: in main chunk

Locals: RingMenu_AddonName = "RingMenu"
RingMenu = <table> {
 shallow_copy = <function> defined @Interface\AddOns\RingMenu\copy.lua:4
 update_with_defaults = <function> defined @Interface\AddOns\RingMenu\copy.lua:26
 deep_copy = <function> defined @Interface\AddOns\RingMenu\copy.lua:13
}
(*temporary) = nil
(*temporary) = "Masque"
(*temporary) = true
(*temporary) = "attempt to call global 'LibStub' (a nil value)"

**Comment by kbmorales** [comment]
Sorry for the comment spam! One final note:

This was only in the latest release (v.2.2.0). Using instead v.2.1.1 seems to work fine!

**Comment by jsb** [comment]
That's indeed a bug. I was only able to reproduce it when I disabled all other AddOns except RingMenu. Seems like I'm not properly loading the local LibStub.

**Comment by jsb** [comment]
Fixed in 4401b8fbe157f094ae5384283a3e3216f56d882e, which is included with version [2.2.1](https://github.com/jsb/RingMenu/releases/tag/v2.2.1). Thank you for reporting this issue!

**Comment by kbmorales** [comment]
Thank you for a rad add on!
