### ISSUE TITLE
 attempt to index global `RingMenu_settings' (a nil value)

### ISSUE THREAD

**Issue by Gurkzen** [jsb/RingMenu#8]
Hi there! Whenever I login or try to use /ringmenu I get this error:
"Interface\Addons\Ringmenu\Ringmenu.lua:51(*) attempt to index global `RingMenu_settings' (a nil value)"

*(This number can either be 29, 51 or 163)

The menu also looks like this whenever I open it:
![image](https://cloud.githubusercontent.com/assets/24947480/21702990/41343df0-d3af-11e6-84c4-20252fbd9c5f.png)

**Comment by jsb** [comment]
Looks like your settings got messed up somehow, let me look into it. Meanwhile, you can try deleting your RingMenu settings file, i.e. `WoW/Account/ACCOUNTNAME/SERVERNAME/CHARACTERNAME/SavedVariables/RingMenu.lua`.

**Comment by Gurkzen** [comment]
That fixed it, thank you!
