### ISSUE TITLE
Anyway to make patch or get to work with pfUI??

### ISSUE THREAD

**Issue by afuzzybunny408** [jsb/RingMenu#9]
please if you could get this to work with pfUI that would be amazing
[https://github.com/shagu/pfUI](url)

the problem is that when i bring up the menu with the button the slots dont show up and i cant place anything where there would be a slot

**Comment by afuzzybunny408** [comment]
i was able to get it to work by scrolling to the second bar and adding it manualy but i couldnt drag and drop straight to the ring so i guess nevermind

**Comment by jsb** [comment]
I'll check out pfUI to find out where the problem is.

**Comment by tsheeley** [comment]
I didn't have any problems dropping commands directly on the ring while using pfUI. This is a pretty awesome addon!
